<?php
    $user=I('user');
    $pass=I('pass');
    $nickname=I('nickname');
    $repass=I('repass');
    $email=I('email');
    if(!XModel::isEmail($email)){
        PR(300,"邮箱格式不正确，请检查重新填写");
    }
    if(strlen($user)>16||strlen($pass)>16){
        PR(300,"用户名或密码最长不能超过16位");
    }
    if(strlen($pass)<6||strlen($user)<6){
        PR(300,"用户名或密码长度不能小于6位");
    }
    if(!preg_match('/^[a-zA-Z0-9]+$/u',$user)){
        PR(300,"账号只能由字母和数字构成");
    }
    if($pass!=$repass){
        PR(300,"两次密码不一致，请检查重新填写");
    }
    $checkEmail=M('user')->where(['email'=>$email])->find();
    if($checkEmail!=false){
        PR(300,"已经有账号绑定此邮箱");
    }
    $data=M('user')->where(['user'=>$user])->find();
    if($data==false){
        using("Mail/Email");
        Email::Send($email,"欢迎加入中文社区","<h1>欢迎注册SC中文社区，社区正在努力建设中，如果你有建议或疑问请加入SCAPI-Mod教学群(638052328)进行讨论</h1>");
        M('user')->add(['user'=>$user,'passwd'=>md5($pass),'last_login_time'=>time(),'token'=>XModel::makeToken(),'nickname'=>$nickname,'authority'=>'[0]','flags'=>'[4]','regtime'=>time(),'loginip'=>$_SERVER['REMOTE_ADDR'],'email'=>$email]);
        PR(200,"注册成功");
    }else{
        PR(300,"账号已存在");
    }
