<?php
using("model/ModList");
$itemid=intval($urlparams['_p0']);
$itemdata=M("modwords")->where(['id'=>$itemid])->find();
$modid=intval($itemdata['modid']);
$data=M('modlist')->where(['id'=>$modid])->find();
if($data==false)XModel::error("参数错误");
//获得release列表
//$itemlist=M("modrelease")->where(['modid'=>$modid])->order('addTime','desc')->limit($page*5,5)->select();
XModel::Set('flagshtml',ModList::getModsFlags($data['modflags']));
XModel::Set('modname',$data['fullname']);
XModel::Set('id',$modid);
XModel::Set('moddesc',$data['description']);
XModel::Set('title',$itemdata['title']);
XModel::Set('content',$itemdata['content']);
XModel::Load("worditem","mods",false);